# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pattern-MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pattern-MVVM
    pod 'Alamofire', '~> 4.9.1'
    pod 'Kingfisher', '~> 5.15.0'
    pod 'SwiftLint', '~> 0.40.0'

  target 'Pattern-MVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pattern-MVVMUITests' do
    # Pods for testing
  end

end
